### ISSUE TITLE
Add a method for selecting which package to run in a container

### ISSUE THREAD

**Issue by HT154** [habitat-sh/habitat-operator#234]
The Habitat Docker exporter supports exporting images with multiple packages installed. This is great for when you have multiple services that share a codebase like many Python or Ruby web apps because it allows exporting a single container that can run all of your app's services. Here's an example:

Habitat Plans:
• service-base - packages the app code, installs dependencies
• service-web - depends on service-base, symlinks app files into svc_var_path, has run hook for web entry point
• service-worker - depends on service-base, symlinks app files into svc_var_path, has run hook for worker entry point

Docker export (in studio):
```bash
# build all three plans first
hab pkg export docker -i <origin>/service-all results/<origin>-service-base-<version>-<timestamp>-x86_64-linux.hart results/<origin>-service-web-<version>-<timestamp>-x86_64-linux.hart results/<origin>-service-worker-<version>-<timestamp>-x86_64-linux.hart
```

This results in a container with this init.sh entry point:
```bash
#!/hab/pkgs/core/busybox-static/1.24.2/20170513215502/bin/sh
export PATH="/bin"
case "$1" in
  -h|--help|help|-V|--version) exec /bin/hab sup "$@";;
  -*) exec /bin/hab sup start <origin>/service-base "$@";;
  *) exec /bin/hab sup "$@";;
esac
```

I'd now like to set this up with k8s resources:
```yaml
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: service-web
spec:
  image: <origin>/service-all
  count: 1
  service:
    name: service-web
    topology: standalone
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: service-worker
spec:
  image: <origin>/service-all
  count: 1
  service:
    name: service-worker
    topology: standalone
```

The resulting StatefulSet objects will always have their first container args begin with a dash (either "--group" or "--topology") so the init.sh `-*)` case is taken. This attempts to start the base package, which doesn't even have a run hook. Dang.

### Possible Solutions

I can think of two ways to handle this. Both require minor updates to the Habitat resource.

#### Implicit: add an origin field to spec.service

```yaml
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: service-<type>
spec:
  image: <origin>/service-all
  count: 1
  service:
    name: service-<type>
    origin: <origin>
    topology: standalone
```

This would cause `habArgs` to be initialized with the contents `['start', '<origin>/service-<type>']`. The package ident arg is created from spec.service.name and spec.service.origin
(ref https://github.com/habitat-sh/habitat-operator/blob/master/pkg/controller/stateful_sets.go#L38)

If no origin is set, fall back on the old behavior of using an empty array, resulting in starting the package specified in init.sh.

#### Explicit: add a baseArgs field to spec

```yaml
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: service-worker
spec:
  image: <origin>/service-all
  count: 1
  baseArgs: ['start', '<origin>/service-<type>']
  service:
    name: service-<type>
    origin: <origin>
    topology: standalone
```

This would also cause `habArgs` to be initialized with the contents `['start', '<origin>/service-<type>']`. However, in this case, the exact args prefix is specified.

If no baseArgs are set, fall back on the old behavior of using an empty array, resulting in starting the package specified in init.sh.
